"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FIFA 16 Auto Buyer.py']
DATA_FILES = ['images','fonts','config']
OPTIONS = {'argv_emulation': True, 'iconfile': './logo.icns'}

with open('requirements.txt') as f:
    requires = f.read().splitlines()

setup(
    install_requires=requires,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
